import pandas as pd
from typing import List, Dict, Any

try:
    from temporal_features import extract_temporal_features
    from behavioral_features import extract_behavioral_features
except ImportError:
    from agent.features.temporal_features import extract_temporal_features
    from agent.features.behavioral_features import extract_behavioral_features

def build_features(raw_logs: List[Dict[str, Any]]) -> pd.DataFrame:
    """
    Orchestrate the feature extraction process from raw event dictionaries.
    
    Args:
        raw_logs: List of dictionaries representing parsed log events.
        
    Returns:
        Pandas DataFrame containing original logs and appended feature columns.
    """
    if not raw_logs:
        return pd.DataFrame()
        
    df = pd.DataFrame(raw_logs)
    
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    # Apply feature extraction layers
    df = extract_temporal_features(df)
    df = extract_behavioral_features(df)
    
    # Fill NaNs generated by rolling operations or missing data
    df.fillna(0, inplace=True)
    
    # Define expected feature columns
    feature_cols = [
        'hour_sin', 'hour_cos', 'is_off_hours', 'is_weekend',
        'time_since_last_event_ip', 'unique_users_15m',
        'failures_15m', 'successes_15m', 'failure_ratio_15m'
    ]
    
    # Define expected metadata columns
    metadata_cols = [
        'id', 'timestamp', 'hostname', 'process', 'pid', 'event_type', 
        'username', 'src_ip', 'src_port', 'raw_message'
    ]
    
    # Ensure all final columns exist, even if empty/missing
    for col in feature_cols:
        if col not in df.columns:
            df[col] = 0.0
            
    # Include only available metadata to prevent KeyErrors
    available_metadata = [col for col in metadata_cols if col in df.columns]
    
    # Return structured DataFrame
    return df[available_metadata + feature_cols]
