import re
import datetime
import logging
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

# Typical SSH syslog format:
# Mar 01 12:34:56 server-01 sshd[1234]: Accepted publickey for user from 192.168.1.1 port 50000 ssh2...
# Mar 01 12:34:56 server-01 sshd[1234]: Failed password for root from ...
# Mar 01 12:34:56 server-01 sshd[1234]: pam_unix(sshd:session): session opened for user ...

SYSLOG_PATTERN = re.compile(
    r"^(?P<month>[A-Z][a-z]{2})\s+(?P<day>\d{1,2})\s+(?P<time>\d{2}:\d{2}:\d{2})\s+"
    r"(?P<host>\S+)\s+(?P<process>[A-Za-z_-]+)\[(?P<pid>\d+)\]:\s+(?P<message>.*)$"
)

def parse_syslog_sshd(log_line: str, year: int = datetime.datetime.now().year) -> Optional[Dict[str, Any]]:
    """
    Parse a standard syslog line generated by sshd.
    
    Args:
        log_line (str): The raw log string.
        year (int, optional): The year to attach, since syslog often omits it. Defaults to current year.
        
    Returns:
        Optional[Dict[str, Any]]: A dictionary containing the parsed event data, or None if parsing fails.
    """
    match = SYSLOG_PATTERN.match(log_line)
    if not match:
        logger.debug(f"Failed to parse syslog baseline: {log_line}")
        return None
        
    groups = match.groupdict()
    
    try:
        # Parse timestamp
        # E.g., 'Mar 11 15:30:00' + year -> datetime
        date_str = f"{year} {groups['month']} {groups['day']} {groups['time']}"
        timestamp = datetime.datetime.strptime(date_str, "%Y %b %d %H:%M:%S")
    except ValueError as e:
        logger.error(f"Error parsing date {date_str}: {e}")
        return None

    event_data = {
        "timestamp": timestamp,
        "hostname": groups['host'],
        "process": groups['process'],
        "pid": int(groups['pid']),
        "raw_message": groups['message'].strip()
    }

    # Further parse the specific SSH message
    # Default values
    event_data["event_type"] = "unknown"
    event_data["username"] = None
    event_data["src_ip"] = None
    event_data["src_port"] = None

    msg = event_data["raw_message"]

    # Pattern for Failed/Accepted auth
    # "Failed password for [invalid user] <user> from <ip> port <port> ssh2"
    # "Accepted publickey for <user> from <ip> port <port> ssh2"
    auth_match = re.search(r"(Failed|Accepted)\s+(password|publickey)\s+(?:for invalid user\s+)?(?:for\s+)?(\S+)\s+from\s+(\S+)\s+port\s+(\d+)", msg)
    
    if auth_match:
        status = auth_match.group(1).lower()
        method = auth_match.group(2).lower()
        user = auth_match.group(3)
        ip = auth_match.group(4)
        port = auth_match.group(5)
        
        event_data["event_type"] = f"{status}_{method}"
        event_data["username"] = user
        event_data["src_ip"] = ip
        event_data["src_port"] = int(port)
        
    elif "session opened for user" in msg:
        session_match = re.search(r"session opened for user\s+(\S+)", msg)
        if session_match:
            event_data["event_type"] = "session_opened"
            event_data["username"] = session_match.group(1)
            
    elif "Disconnecting" in msg:
        event_data["event_type"] = "disconnected"
        user_match = re.search(r"user\s+(\S+)", msg)
        ip_match = re.search(r"(\d+\.\d+\.\d+\.\d+)", msg)
        if user_match:
            event_data["username"] = user_match.group(1)
        if ip_match:
            event_data["src_ip"] = ip_match.group(1)
            
    # Add other SSH log type parsing if needed here
    
    return event_data
